%%{init: {'theme': 'default', 'themeVariables': { 'fontSize': '18px' }, 'flowchart': { 'nodeSpacing': 25, 'rankSpacing': 25 }}}%%
flowchart LR
  %% Arquitectura Medallion
  
  subgraph Sources["Fuentes Gratuitas"]
    YF["Yahoo Finance (yfinance)"]
    GDELT["GDELT API v2"]
    VD["Databricks Volume (static data)"]
  end

  subgraph Databricks["Databricks"]
    direction TB

    subgraph Bronze["Bronze (Raw)"]
      U["universe_sp100_snapshot.csv (Snapshot S&amp;P 100)"]
      TA["ticker_aliases.csv (enterprise alias)"]
      P["prices_raw (yfinance finance data)"]
      GT["gdelt_tonechart (GDELT news tone)"]
    end

    subgraph Silver["Silver (Curado)"]
      PD["prices_daily (finance metrics)"]
      TT["ticker_news_tone (news tone by ticker)"]
    end

    subgraph Gold["Gold (ML Ready)"]
      PTD["ticker_predictor_training_dataset"]
    end

    O["pipeline_prediction_training_dataset job"]
  end

  %% Data flow
  YF --> O
  VD --> |"universe_sp100_snapshot.csv from TradingView"| U
  VD --> |"ticker_aliases.csv"| TA
  GDELT --> O

  %% bronze (ingestion)

  O --> |"A1-bronze-get_finance_data"| P
  O --> |"B1-bronze-gdelt_news_tone"| GT

  %% bronze to silver 

  P --> |"A2-silver-process_finance_data"| PD
  GT --> |"B2-silver-process_news_data"| TT
  U --> PD
  U --> TT
  TA --> PD

  %% silver to gold
  PD --> |"gold-data_presentation"| PTD
  TT --> |"gold-data_presentation"| PTD
